server:
  port: 10000

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Automatically create/update tables (use 'none' for production)
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true # Enable SQL comments in logs
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 40MB
      max-request-size: 40MB
