#server
server:
  port: 10000

spring:
  datasource:
    hikari:
      #postgreSQL
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432:db명
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update # Automatically create/update tables (use 'none' for production)
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true # Enable SQL comments in logs

  servlet:
    multipart:
      enabled: true
      max-file-size: 40MB
      max-request-size: 40MB

