name: Deploy Sirius App to Docker Hub

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed  # Triggered when PR is closed (merged)

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base branch code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Generate application.yaml from template
        run: |
          envsubst < src/main/resources/application-template.yml > src/main/resources/application.yml
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sirius:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/sirius:latest
