name: Deploy Sirius App to Docker Hub

on:
  pull_request:
    branches:
      - master
    types:
      - closed # Trigger when the PR is closed (merged)

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sirius:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/sirius:latest
